export default [
  {
    login: "ermolnik",
    id: 15360278,
    node_id: "MDQ6VXNlcjE1MzYwMjc4",
    avatar_url: "https://avatars.githubusercontent.com/u/15360278?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ermolnik",
    html_url: "https://github.com/ermolnik",
    followers_url: "https://api.github.com/users/ermolnik/followers",
    following_url:
      "https://api.github.com/users/ermolnik/following{/other_user}",
    gists_url: "https://api.github.com/users/ermolnik/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ermolnik/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ermolnik/subscriptions",
    organizations_url: "https://api.github.com/users/ermolnik/orgs",
    repos_url: "https://api.github.com/users/ermolnik/repos",
    events_url: "https://api.github.com/users/ermolnik/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ermolnik/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jasineri",
    id: 17604010,
    node_id: "MDQ6VXNlcjE3NjA0MDEw",
    avatar_url: "https://avatars.githubusercontent.com/u/17604010?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jasineri",
    html_url: "https://github.com/jasineri",
    followers_url: "https://api.github.com/users/jasineri/followers",
    following_url:
      "https://api.github.com/users/jasineri/following{/other_user}",
    gists_url: "https://api.github.com/users/jasineri/gists{/gist_id}",
    starred_url: "https://api.github.com/users/jasineri/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jasineri/subscriptions",
    organizations_url: "https://api.github.com/users/jasineri/orgs",
    repos_url: "https://api.github.com/users/jasineri/repos",
    events_url: "https://api.github.com/users/jasineri/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/jasineri/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mxmnk",
    id: 46030850,
    node_id: "MDQ6VXNlcjQ2MDMwODUw",
    avatar_url: "https://avatars.githubusercontent.com/u/46030850?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mxmnk",
    html_url: "https://github.com/mxmnk",
    followers_url: "https://api.github.com/users/mxmnk/followers",
    following_url: "https://api.github.com/users/mxmnk/following{/other_user}",
    gists_url: "https://api.github.com/users/mxmnk/gists{/gist_id}",
    starred_url: "https://api.github.com/users/mxmnk/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mxmnk/subscriptions",
    organizations_url: "https://api.github.com/users/mxmnk/orgs",
    repos_url: "https://api.github.com/users/mxmnk/repos",
    events_url: "https://api.github.com/users/mxmnk/events{/privacy}",
    received_events_url: "https://api.github.com/users/mxmnk/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "joshcallander",
    id: 47772024,
    node_id: "MDQ6VXNlcjQ3NzcyMDI0",
    avatar_url: "https://avatars.githubusercontent.com/u/47772024?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/joshcallander",
    html_url: "https://github.com/joshcallander",
    followers_url: "https://api.github.com/users/joshcallander/followers",
    following_url:
      "https://api.github.com/users/joshcallander/following{/other_user}",
    gists_url: "https://api.github.com/users/joshcallander/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/joshcallander/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/joshcallander/subscriptions",
    organizations_url: "https://api.github.com/users/joshcallander/orgs",
    repos_url: "https://api.github.com/users/joshcallander/repos",
    events_url: "https://api.github.com/users/joshcallander/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/joshcallander/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "zendy199x",
    id: 50132805,
    node_id: "MDQ6VXNlcjUwMTMyODA1",
    avatar_url: "https://avatars.githubusercontent.com/u/50132805?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/zendy199x",
    html_url: "https://github.com/zendy199x",
    followers_url: "https://api.github.com/users/zendy199x/followers",
    following_url:
      "https://api.github.com/users/zendy199x/following{/other_user}",
    gists_url: "https://api.github.com/users/zendy199x/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/zendy199x/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/zendy199x/subscriptions",
    organizations_url: "https://api.github.com/users/zendy199x/orgs",
    repos_url: "https://api.github.com/users/zendy199x/repos",
    events_url: "https://api.github.com/users/zendy199x/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/zendy199x/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Oussama1403",
    id: 64992449,
    node_id: "MDQ6VXNlcjY0OTkyNDQ5",
    avatar_url: "https://avatars.githubusercontent.com/u/64992449?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Oussama1403",
    html_url: "https://github.com/Oussama1403",
    followers_url: "https://api.github.com/users/Oussama1403/followers",
    following_url:
      "https://api.github.com/users/Oussama1403/following{/other_user}",
    gists_url: "https://api.github.com/users/Oussama1403/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Oussama1403/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Oussama1403/subscriptions",
    organizations_url: "https://api.github.com/users/Oussama1403/orgs",
    repos_url: "https://api.github.com/users/Oussama1403/repos",
    events_url: "https://api.github.com/users/Oussama1403/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Oussama1403/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "hacker8853",
    id: 76920935,
    node_id: "MDQ6VXNlcjc2OTIwOTM1",
    avatar_url: "https://avatars.githubusercontent.com/u/76920935?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hacker8853",
    html_url: "https://github.com/hacker8853",
    followers_url: "https://api.github.com/users/hacker8853/followers",
    following_url:
      "https://api.github.com/users/hacker8853/following{/other_user}",
    gists_url: "https://api.github.com/users/hacker8853/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/hacker8853/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/hacker8853/subscriptions",
    organizations_url: "https://api.github.com/users/hacker8853/orgs",
    repos_url: "https://api.github.com/users/hacker8853/repos",
    events_url: "https://api.github.com/users/hacker8853/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/hacker8853/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "japoewn",
    id: 89349062,
    node_id: "MDQ6VXNlcjg5MzQ5MDYy",
    avatar_url: "https://avatars.githubusercontent.com/u/89349062?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/japoewn",
    html_url: "https://github.com/japoewn",
    followers_url: "https://api.github.com/users/japoewn/followers",
    following_url:
      "https://api.github.com/users/japoewn/following{/other_user}",
    gists_url: "https://api.github.com/users/japoewn/gists{/gist_id}",
    starred_url: "https://api.github.com/users/japoewn/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/japoewn/subscriptions",
    organizations_url: "https://api.github.com/users/japoewn/orgs",
    repos_url: "https://api.github.com/users/japoewn/repos",
    events_url: "https://api.github.com/users/japoewn/events{/privacy}",
    received_events_url: "https://api.github.com/users/japoewn/received_events",
    type: "User",
    site_admin: false,
  },
];
