export default {
  login: "ramandeep5176",
  id: 84944025,
  node_id: "MDQ6VXNlcjg0OTQ0MDI1",
  avatar_url: "https://avatars.githubusercontent.com/u/84944025?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ramandeep5176",
  html_url: "https://github.com/ramandeep5176",
  followers_url: "https://api.github.com/users/ramandeep5176/followers",
  following_url:
    "https://api.github.com/users/ramandeep5176/following{/other_user}",
  gists_url: "https://api.github.com/users/ramandeep5176/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/ramandeep5176/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ramandeep5176/subscriptions",
  organizations_url: "https://api.github.com/users/ramandeep5176/orgs",
  repos_url: "https://api.github.com/users/ramandeep5176/repos",
  events_url: "https://api.github.com/users/ramandeep5176/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/ramandeep5176/received_events",
  type: "User",
  site_admin: false,
  name: "Raman Gill",
  company: null,
  blog: "https://raman1.netlify.app",
  location: "canada,ontario",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 45,
  public_gists: 0,
  followers: 8,
  following: 9,
  created_at: "2021-05-27T23:57:16Z",
  updated_at: "2021-08-20T20:25:15Z",
};
